subroutine admint2 (AMP, F, P, NOUT, AMPIN2, IDTIN, PHIN2, NIN, ITIN)
    !f2py intent(in) AMPIN2,IDTIN,PHIN2,NIN,ITIN
    !f2py intent(out) AMP,F,P,NOUT
    !+
    !  - - - - - - - - - - -
    !   A D M I N T
    !  - - - - - - - - - - -
    !
    !  This routine is part of the International Earth Rotation and
    !  Reference Systems Service (IERS) Conventions software collection.
    !
    !  This subroutine returns the ocean loading displacement amplitude,
    !  frequency, and phase of a set of tidal constituents generated by
    !  the Bos-Scherneck website at http://www.oso.chalmers.se/~loading/.
    !  The variable nin is input as the number wanted, and the variable
    !  nout is returned as the number provided.  The constituents used
    !  are stored in the arrays idd (Doodson number) and tamp
    !  (Cartwright-Edden amplitude).  The actual amp and phase of each
    !  of these are determined by spline interpolation of the real and
    !  imaginary part of the admittance, as specified at a subset of the
    !  constituents.
    !
    !  In general, Class 1, 2, and 3 models represent physical effects that
    !  act on geodetic parameters while canonical models provide lower-level
    !  representations or basic computations that are used by Class 1, 2, or
    !  3 models.
    !
    !  Status:  Class 1 model
    !
    !     Class 1 models are those recommended to be used a priori in the
    !     reduction of raw space geodetic data in order to determine
    !     geodetic parameter estimates.
    !     Class 2 models are those that eliminate an observational
    !     singularity and are purely conventional in nature.
    !     Class 3 models are those that are not required as either Class
    !     1 or 2.
    !     Canonical models are accepted as is and cannot be classified as
    !     a Class 1, 2, or 3 model.
    !
    !  Given:
    !     AMPIN       d      Cartwright-Edden amplitude of tidal constituents
    !     IDTIN       i      Doodson number of tidal constituents
    !     PHIN        d      Phase of tidal constituents
    !     NIN         i      Number of harmonics used
    !
    !  Returned:
    !     AMP         d      Amplitude due to ocean loading
    !     F           d      Frequency due to ocean loading
    !     P           d      Phase due to ocean loading
    !     NOUT        i      Number of harmonics returned
    !
    !  Notes:
    !
    !  1) The phase is determined for a time set in COMMON block /date/ in
    !     the subroutine TDFRPH.
    !
    !  2) The arrays F and P must be specified as double precision.
    !
    !  Called:
    !     TDFRPH             Returns frequency and phase of a tidal
    !                        constituent with given Doodson number
    !     SPLINE             Sets up array for cubic spline interpolation
    !     EVAL               Performs cubic spline interpolation
    !     SHELLS             Sorts an array using Shell Sort
    !
    !  Test case:
    !     Test cases are provided in the main program HARDISP.F.
    !
    !  References:
    !
    !     McCarthy, D. D., Petit, G. (eds.), IERS Conventions (2003),
    !     IERS Technical Note No. 32, BKG (2004)
    !
    !  Revisions:
    !  2009 June 17 B.E. Stetzler  Initial changes to header
    !  2009 June 18 B.E. Stetzler  Used IMPLICIT NONE, declared more variables,
    !                              and added D0 to DOUBLE PRECISION variables
    !  2009 August 19 B.E.Stetzler Capitalized all variables for FORTRAN 77
    !                              compatibility
    !-----------------------------------------------------------------------

    IMPLICIT NONE
    integer I, J, K, IT, KEY, LL, NCON, NDI, NIN, NLP, NSD, NT, II, KK, ITIN
    integer*8 IDD, IDTIN, NOUT

    !+----------------------------------------------------------------------
    !  The parameters below set the number of harmonics used in the prediction
    !  (nt; This must also be set in the main program) and the number of
    !  constituents whose amp and phase may be specified (ncon)
    !-----------------------------------------------------------------------
    PARAMETER (NT = 342)
    PARAMETER (NCON = 20)

    REAL AIM, DI, DR, DTR, RF, RL, SCR, SDI, SDR, TAMP, ZDI, ZDR, &
            EVAL, AM, RE, SF, AMPIN, PHIN
    DOUBLE PRECISION AMPIN2, PHIN2
    DOUBLE PRECISION AMP, F, FR, P, PR

    !      DIMENSION AMPIN(*),IDTIN(6,*),PHIN(*)
    !      DIMENSION AMP(*),F(*),P(*)
    DIMENSION AMPIN(11), IDTIN(6, 11), PHIN(11), AMPIN2(11), PHIN2(11)
    DIMENSION AMP(342), F(342), P(342)
    DIMENSION ITIN(5)

    !  Arrays containing information about all stored constituents
    DIMENSION IDD(6, NT), TAMP(NT)

    COMMON/DATE/IT(5)

    !  Arrays containing information about the subset whose amp and phase may
    !  be specified, and scratch arrays for the spline routines for which
    !  at most ncon constituents may be specified.

    DIMENSION RL(NCON), AIM(NCON), RF(NCON), KEY(NCON), SCR(NCON), &
            ZDI(NCON), ZDR(NCON), DI(NCON), DR(NCON), SDI(NCON), SDR(NCON)
    DATA DTR/.01745329252/
    DATA RL/NCON*0.0/, AIM/NCON*0.0/, RF/NCON*0.0/
    DATA ZDI/NCON*0.0/, ZDR/NCON*0.0/, DI/NCON*0.0/, DR/NCON*0.0/
    DATA SDI/NCON*0.0/, SDR/NCON*0.0/
    DATA TAMP/&
            .632208, .294107, .121046, .079915, .023818, -.023589, .022994, &
            .019333, -.017871, .017192, .016018, .004671, -.004662, -.004519, &
            .004470, .004467, .002589, -.002455, -.002172, .001972, .001947, &
            .001914, -.001898, .001802, .001304, .001170, .001130, .001061, &
            -.001022, -.001017, .001014, .000901, -.000857, .000855, .000855, &
            .000772, .000741, .000741, -.000721, .000698, .000658, .000654, &
            -.000653, .000633, .000626, -.000598, .000590, .000544, .000479, &
            -.000464, .000413, -.000390, .000373, .000366, .000366, -.000360, &
            -.000355, .000354, .000329, .000328, .000319, .000302, .000279, &
            -.000274, -.000272, .000248, -.000225, .000224, -.000223, -.000216, &
            .000211, .000209, .000194, .000185, -.000174, -.000171, .000159, &
            .000131, .000127, .000120, .000118, .000117, .000108, .000107, &
            .000105, -.000102, .000102, .000099, -.000096, .000095, -.000089, &
            -.000085, -.000084, -.000081, -.000077, -.000072, -.000067, .000066, &
            .000064, .000063, .000063, .000063, .000062, .000062, -.000060, &
            .000056, .000053, .000051, .000050, .368645, -.262232, -.121995, &
            -.050208, .050031, -.049470, .020620, .020613, .011279, -.009530, &
            -.009469, -.008012, .007414, -.007300, .007227, -.007131, -.006644, &
            .005249, .004137, .004087, .003944, .003943, .003420, .003418, &
            .002885, .002884, .002160, -.001936, .001934, -.001798, .001690, &
            .001689, .001516, .001514, -.001511, .001383, .001372, .001371, &
            -.001253, -.001075, .001020, .000901, .000865, -.000794, .000788, &
            .000782, -.000747, -.000745, .000670, -.000603, -.000597, .000542, &
            .000542, -.000541, -.000469, -.000440, .000438, .000422, .000410, &
            -.000374, -.000365, .000345, .000335, -.000321, -.000319, .000307, &
            .000291, .000290, -.000289, .000286, .000275, .000271, .000263, &
            -.000245, .000225, .000225, .000221, -.000202, -.000200, -.000199, &
            .000192, .000183, .000183, .000183, -.000170, .000169, .000168, &
            .000162, .000149, -.000147, -.000141, .000138, .000136, .000136, &
            .000127, .000127, -.000126, -.000121, -.000121, .000117, -.000116, &
            -.000114, -.000114, -.000114, .000114, .000113, .000109, .000108, &
            .000106, -.000106, -.000106, .000105, .000104, -.000103, -.000100, &
            -.000100, -.000100, .000099, -.000098, .000093, .000093, .000090, &
            -.000088, .000083, -.000083, -.000082, -.000081, -.000079, -.000077, &
            -.000075, -.000075, -.000075, .000071, .000071, -.000071, .000068, &
            .000068, .000065, .000065, .000064, .000064, .000064, -.000064, &
            -.000060, .000056, .000056, .000053, .000053, .000053, -.000053, &
            .000053, .000053, .000052, .000050, -.066607, -.035184, -.030988, &
            .027929, -.027616, -.012753, -.006728, -.005837, -.005286, -.004921, &
            -.002884, -.002583, -.002422, .002310, .002283, -.002037, .001883, &
            -.001811, -.001687, -.001004, -.000925, -.000844, .000766, .000766, &
            -.000700, -.000495, -.000492, .000491, .000483, .000437, -.000416, &
            -.000384, .000374, -.000312, -.000288, -.000273, .000259, .000245, &
            -.000232, .000229, -.000216, .000206, -.000204, -.000202, .000200, &
            .000195, -.000190, .000187, .000180, -.000179, .000170, .000153, &
            -.000137, -.000119, -.000119, -.000112, -.000110, -.000110, .000107, &
            -.000095, -.000095, -.000091, -.000090, -.000081, -.000079, -.000079, &
            .000077, -.000073, .000069, -.000067, -.000066, .000065, .000064, &
            -.000062, .000060, .000059, -.000056, .000055, -.000051/
    DATA IDD/&
            2, 0, 0, 0, 0, 0, 2, 2, -2, 0, 0, 0, 2, -1, 0, 1, 0, 0, &
            2, 2, 0, 0, 0, 0, 2, 2, 0, 0, 1, 0, 2, 0, 0, 0, -1, 0, &
            2, -1, 2, -1, 0, 0, 2, -2, 2, 0, 0, 0, 2, 1, 0, -1, 0, 0, &
            2, 2, -3, 0, 0, 1, 2, -2, 0, 2, 0, 0, 2, -3, 2, 1, 0, 0, &
            2, 1, -2, 1, 0, 0, 2, -1, 0, 1, -1, 0, 2, 3, 0, -1, 0, 0, &
            2, 1, 0, 1, 0, 0, 2, 2, 0, 0, 2, 0, 2, 2, -1, 0, 0, -1, &
            2, 0, -1, 0, 0, 1, 2, 1, 0, 1, 1, 0, 2, 3, 0, -1, 1, 0, &
            2, 0, 1, 0, 0, -1, 2, 0, -2, 2, 0, 0, 2, -3, 0, 3, 0, 0, &
            2, -2, 3, 0, 0, -1, 2, 4, 0, 0, 0, 0, 2, -1, 1, 1, 0, -1, &
            2, -1, 3, -1, 0, -1, 2, 2, 0, 0, -1, 0, 2, -1, -1, 1, 0, 1, &
            2, 4, 0, 0, 1, 0, 2, -3, 4, -1, 0, 0, 2, -1, 2, -1, -1, 0, &
            2, 3, -2, 1, 0, 0, 2, 1, 2, -1, 0, 0, 2, -4, 2, 2, 0, 0, &
            2, 4, -2, 0, 0, 0, 2, 0, 2, 0, 0, 0, 2, -2, 2, 0, -1, 0, &
            2, 2, -4, 0, 0, 2, 2, 2, -2, 0, -1, 0, 2, 1, 0, -1, -1, 0, &
            2, -1, 1, 0, 0, 0, 2, 2, -1, 0, 0, 1, 2, 2, 1, 0, 0, -1, &
            2, -2, 0, 2, -1, 0, 2, -2, 4, -2, 0, 0, 2, 2, 2, 0, 0, 0, &
            2, -4, 4, 0, 0, 0, 2, -1, 0, -1, -2, 0, 2, 1, 2, -1, 1, 0, &
            2, -1, -2, 3, 0, 0, 2, 3, -2, 1, 1, 0, 2, 4, 0, -2, 0, 0, &
            2, 0, 0, 2, 0, 0, 2, 0, 2, -2, 0, 0, 2, 0, 2, 0, 1, 0, &
            2, -3, 3, 1, 0, -1, 2, 0, 0, 0, -2, 0, 2, 4, 0, 0, 2, 0, &
            2, 4, -2, 0, 1, 0, 2, 0, 0, 0, 0, 2, 2, 1, 0, 1, 2, 0, &
            2, 0, -2, 0, -2, 0, 2, -2, 1, 0, 0, 1, 2, -2, 1, 2, 0, -1, &
            2, -1, 1, -1, 0, 1, 2, 5, 0, -1, 0, 0, 2, 1, -3, 1, 0, 1, &
            2, -2, -1, 2, 0, 1, 2, 3, 0, -1, 2, 0, 2, 1, -2, 1, -1, 0, &
            2, 5, 0, -1, 1, 0, 2, -4, 0, 4, 0, 0, 2, -3, 2, 1, -1, 0, &
            2, -2, 1, 1, 0, 0, 2, 4, 0, -2, 1, 0, 2, 0, 0, 2, 1, 0, &
            2, -5, 4, 1, 0, 0, 2, 0, 2, 0, 2, 0, 2, -1, 2, 1, 0, 0, &
            2, 5, -2, -1, 0, 0, 2, 1, -1, 0, 0, 0, 2, 2, -2, 0, 0, 2, &
            2, -5, 2, 3, 0, 0, 2, -1, -2, 1, -2, 0, 2, -3, 5, -1, 0, -1, &
            2, -1, 0, 0, 0, 1, 2, -2, 0, 0, -2, 0, 2, 0, -1, 1, 0, 0, &
            2, -3, 1, 1, 0, 1, 2, 3, 0, -1, -1, 0, 2, 1, 0, 1, -1, 0, &
            2, -1, 2, 1, 1, 0, 2, 0, -3, 2, 0, 1, 2, 1, -1, -1, 0, 1, &
            2, -3, 0, 3, -1, 0, 2, 0, -2, 2, -1, 0, 2, -4, 3, 2, 0, -1, &
            2, -1, 0, 1, -2, 0, 2, 5, 0, -1, 2, 0, 2, -4, 5, 0, 0, -1, &
            2, -2, 4, 0, 0, -2, 2, -1, 0, 1, 0, 2, 2, -2, -2, 4, 0, 0, &
            2, 3, -2, -1, -1, 0, 2, -2, 5, -2, 0, -1, 2, 0, -1, 0, -1, 1, &
            2, 5, -2, -1, 1, 0, 1, 1, 0, 0, 0, 0, 1, -1, 0, 0, 0, 0, &
            1, 1, -2, 0, 0, 0, 1, -2, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, &
            1, -1, 0, 0, -1, 0, 1, 2, 0, -1, 0, 0, 1, 0, 0, 1, 0, 0, &
            1, 3, 0, 0, 0, 0, 1, -2, 2, -1, 0, 0, 1, -2, 0, 1, -1, 0, &
            1, -3, 2, 0, 0, 0, 1, 0, 0, -1, 0, 0, 1, 1, 0, 0, -1, 0, &
            1, 3, 0, 0, 1, 0, 1, 1, -3, 0, 0, 1, 1, -3, 0, 2, 0, 0, &
            1, 1, 2, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 2, 0, -1, 1, 0, &
            1, 0, 2, -1, 0, 0, 1, 2, -2, 1, 0, 0, 1, 3, -2, 0, 0, 0, &
            1, -1, 2, 0, 0, 0, 1, 1, 1, 0, 0, -1, 1, 1, -1, 0, 0, 1, &
            1, 4, 0, -1, 0, 0, 1, -4, 2, 1, 0, 0, 1, 0, -2, 1, 0, 0, &
            1, -2, 2, -1, -1, 0, 1, 3, 0, -2, 0, 0, 1, -1, 0, 2, 0, 0, &
            1, -1, 0, 0, -2, 0, 1, 3, 0, 0, 2, 0, 1, -3, 2, 0, -1, 0, &
            1, 4, 0, -1, 1, 0, 1, 0, 0, -1, -1, 0, 1, 1, -2, 0, -1, 0, &
            1, -3, 0, 2, -1, 0, 1, 1, 0, 0, 2, 0, 1, 1, -1, 0, 0, -1, &
            1, -1, -1, 0, 0, 1, 1, 0, 2, -1, 1, 0, 1, -1, 1, 0, 0, -1, &
            1, -1, -2, 2, 0, 0, 1, 2, -2, 1, 1, 0, 1, -4, 0, 3, 0, 0, &
            1, -1, 2, 0, 1, 0, 1, 3, -2, 0, 1, 0, 1, 2, 0, -1, -1, 0, &
            1, 0, 0, 1, -1, 0, 1, -2, 2, 1, 0, 0, 1, 4, -2, -1, 0, 0, &
            1, -3, 3, 0, 0, -1, 1, -2, 1, 1, 0, -1, 1, -2, 3, -1, 0, -1, &
            1, 0, -2, 1, -1, 0, 1, -2, -1, 1, 0, 1, 1, 4, -2, 1, 0, 0, &
            1, -4, 4, -1, 0, 0, 1, -4, 2, 1, -1, 0, 1, 5, -2, 0, 0, 0, &
            1, 3, 0, -2, 1, 0, 1, -5, 2, 2, 0, 0, 1, 2, 0, 1, 0, 0, &
            1, 1, 3, 0, 0, -1, 1, -2, 0, 1, -2, 0, 1, 4, 0, -1, 2, 0, &
            1, 1, -4, 0, 0, 2, 1, 5, 0, -2, 0, 0, 1, -1, 0, 2, 1, 0, &
            1, -2, 1, 0, 0, 0, 1, 4, -2, 1, 1, 0, 1, -3, 4, -2, 0, 0, &
            1, -1, 3, 0, 0, -1, 1, 3, -3, 0, 0, 1, 1, 5, -2, 0, 1, 0, &
            1, 1, 2, 0, 1, 0, 1, 2, 0, 1, 1, 0, 1, -5, 4, 0, 0, 0, &
            1, -2, 0, -1, -2, 0, 1, 5, 0, -2, 1, 0, 1, 1, 2, -2, 0, 0, &
            1, 1, -2, 2, 0, 0, 1, -2, 2, 1, 1, 0, 1, 0, 3, -1, 0, -1, &
            1, 2, -3, 1, 0, 1, 1, -2, -2, 3, 0, 0, 1, -1, 2, -2, 0, 0, &
            1, -4, 3, 1, 0, -1, 1, -4, 0, 3, -1, 0, 1, -1, -2, 2, -1, 0, &
            1, -2, 0, 3, 0, 0, 1, 4, 0, -3, 0, 0, 1, 0, 1, 1, 0, -1, &
            1, 2, -1, -1, 0, 1, 1, 2, -2, 1, -1, 0, 1, 0, 0, -1, -2, 0, &
            1, 2, 0, 1, 2, 0, 1, 2, -2, -1, -1, 0, 1, 0, 0, 1, 2, 0, &
            1, 0, 1, 0, 0, 0, 1, 2, -1, 0, 0, 0, 1, 0, 2, -1, -1, 0, &
            1, -1, -2, 0, -2, 0, 1, -3, 1, 0, 0, 1, 1, 3, -2, 0, -1, 0, &
            1, -1, -1, 0, -1, 1, 1, 4, -2, -1, 1, 0, 1, 2, 1, -1, 0, -1, &
            1, 0, -1, 1, 0, 1, 1, -2, 4, -1, 0, 0, 1, 4, -4, 1, 0, 0, &
            1, -3, 1, 2, 0, -1, 1, -3, 3, 0, -1, -1, 1, 1, 2, 0, 2, 0, &
            1, 1, -2, 0, -2, 0, 1, 3, 0, 0, 3, 0, 1, -1, 2, 0, -1, 0, &
            1, -2, 1, -1, 0, 1, 1, 0, -3, 1, 0, 1, 1, -3, -1, 2, 0, 1, &
            1, 2, 0, -1, 2, 0, 1, 6, -2, -1, 0, 0, 1, 2, 2, -1, 0, 0, &
            1, -1, 1, 0, -1, -1, 1, -2, 3, -1, -1, -1, 1, -1, 0, 0, 0, 2, &
            1, -5, 0, 4, 0, 0, 1, 1, 0, 0, 0, -2, 1, -2, 1, 1, -1, -1, &
            1, 1, -1, 0, 1, 1, 1, 1, 2, 0, 0, -2, 1, -3, 1, 1, 0, 0, &
            1, -4, 4, -1, -1, 0, 1, 1, 0, -2, -1, 0, 1, -2, -1, 1, -1, 1, &
            1, -3, 2, 2, 0, 0, 1, 5, -2, -2, 0, 0, 1, 3, -4, 2, 0, 0, &
            1, 1, -2, 0, 0, 2, 1, -1, 4, -2, 0, 0, 1, 2, 2, -1, 1, 0, &
            1, -5, 2, 2, -1, 0, 1, 1, -3, 0, -1, 1, 1, 1, 1, 0, 1, -1, &
            1, 6, -2, -1, 1, 0, 1, -2, 2, -1, -2, 0, 1, 4, -2, 1, 2, 0, &
            1, -6, 4, 1, 0, 0, 1, 5, -4, 0, 0, 0, 1, -3, 4, 0, 0, 0, &
            1, 1, 2, -2, 1, 0, 1, -2, 1, 0, -1, 0, 0, 2, 0, 0, 0, 0, &
            0, 1, 0, -1, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 1, 0, &
            0, 2, 0, 0, 1, 0, 0, 3, 0, -1, 0, 0, 0, 1, -2, 1, 0, 0, &
            0, 2, -2, 0, 0, 0, 0, 3, 0, -1, 1, 0, 0, 0, 1, 0, 0, -1, &
            0, 2, 0, -2, 0, 0, 0, 2, 0, 0, 2, 0, 0, 3, -2, 1, 0, 0, &
            0, 1, 0, -1, -1, 0, 0, 1, 0, -1, 1, 0, 0, 4, -2, 0, 0, 0, &
            0, 1, 0, 1, 0, 0, 0, 0, 3, 0, 0, -1, 0, 4, 0, -2, 0, 0, &
            0, 3, -2, 1, 1, 0, 0, 3, -2, -1, 0, 0, 0, 4, -2, 0, 1, 0, &
            0, 0, 2, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 4, 0, -2, 1, 0, &
            0, 3, 0, -1, 2, 0, 0, 5, -2, -1, 0, 0, 0, 1, 2, -1, 0, 0, &
            0, 1, -2, 1, -1, 0, 0, 1, -2, 1, 1, 0, 0, 2, -2, 0, -1, 0, &
            0, 2, -3, 0, 0, 1, 0, 2, -2, 0, 1, 0, 0, 0, 2, -2, 0, 0, &
            0, 1, -3, 1, 0, 1, 0, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 1, &
            0, 1, 2, -1, 1, 0, 0, 3, 0, -3, 0, 0, 0, 2, 1, 0, 0, -1, &
            0, 1, -1, -1, 0, 1, 0, 1, 0, 1, 2, 0, 0, 5, -2, -1, 1, 0, &
            0, 2, -1, 0, 0, 1, 0, 2, 2, -2, 0, 0, 0, 1, -1, 0, 0, 0, &
            0, 5, 0, -3, 0, 0, 0, 2, 0, -2, 1, 0, 0, 1, 1, -1, 0, -1, &
            0, 3, -4, 1, 0, 0, 0, 0, 2, 0, 2, 0, 0, 2, 0, -2, -1, 0, &
            0, 4, -3, 0, 0, 1, 0, 3, -1, -1, 0, 1, 0, 0, 2, 0, 0, -2, &
            0, 3, -3, 1, 0, 1, 0, 2, -4, 2, 0, 0, 0, 4, -2, -2, 0, 0, &
            0, 3, 1, -1, 0, -1, 0, 5, -4, 1, 0, 0, 0, 3, -2, -1, -1, 0, &
            0, 3, -2, 1, 2, 0, 0, 4, -4, 0, 0, 0, 0, 6, -2, -2, 0, 0, &
            0, 5, 0, -3, 1, 0, 0, 4, -2, 0, 2, 0, 0, 2, 2, -2, 1, 0, &
            0, 0, 4, 0, 0, -2, 0, 3, -1, 0, 0, 0, 0, 3, -3, -1, 0, 1, &
            0, 4, 0, -2, 2, 0, 0, 1, -2, -1, -1, 0, 0, 2, -1, 0, 0, -1, &
            0, 4, -4, 2, 0, 0, 0, 2, 1, 0, 1, -1, 0, 3, -2, -1, 1, 0, &
            0, 4, -3, 0, 1, 1, 0, 2, 0, 0, 3, 0, 0, 6, -4, 0, 0, 0/

    !  Initialize variables.
    K = 0
    NLP = 0
    NDI = 0
    NSD = 0

    IT = int(ITIN)

    !      print *, IDTIN(1:6,11)
    AMPIN = real(AMPIN2)
    PHIN = real(PHIN2)

    DO LL = 1, NIN
        !  See if Doodson numbers match
        DO KK = 1, NT
            II = 0
            DO I = 1, 6
                II = II + abs(IDD(I, KK) - IDTIN(I, LL))
                !      print *, 'I=', I, 'KK=', KK, 'LL=', LL
                !      print *, IDD(I,KK),IDTIN(I,LL),abs(IDD(I,KK)-IDTIN(I,LL))
            ENDDO
            IF(II.EQ.0) GO TO 5
        ENDDO
        !  If you have a match, put line into array
        5       IF(II.EQ.0.AND.K.LT.NCON) THEN
            K = K + 1
            RL(K) = AMPIN(LL) * COS(DTR * PHIN(LL)) / ABS(TAMP(KK))
            AIM(K) = AMPIN(LL) * SIN(DTR * PHIN(LL)) / ABS(TAMP(KK))
            !+---------------------------------------------------------------------
            !  Now have real and imaginary parts of admittance, scaled by Cartwright-
            !  Edden amplitude. Admittance phase is whatever was used in the original
            !  expression. (Usually phase is given relative to some reference,
            !  but amplitude is in absolute units). Next get frequency.
            !----------------------------------------------------------------------
            CALL TDFRPH(IDD(1, KK), FR, PR)
            RF(K) = FR
        ENDIF
    ENDDO

    !      pause
    !+---------------------------------------------------------------------
    !  Done going through constituents; there are k of them.
    !  Have specified admittance at a number of points. Sort these by frequency
    !  and separate diurnal and semidiurnal, recopying admittances to get them
    !  in order using Shell Sort.
    !----------------------------------------------------------------------

    CALL SHELLS(RF, KEY, K)
    DO I = 1, K
        IF(RF(I).LT.0.5) NLP = NLP + 1
        IF(RF(I).LT.1.5.AND.RF(I).GT.0.5) NDI = NDI + 1
        IF(RF(I).LT.2.5.AND.RF(I).GT.1.5) NSD = NSD + 1
        SCR(I) = RL(KEY(I))
    ENDDO
    !      print *, SCR
    !      pause
    DO I = 1, K
        RL(I) = SCR(I)
        SCR(I) = AIM(KEY(I))
    ENDDO
    DO I = 1, K
        AIM(I) = SCR(I)
    ENDDO
    !+---------------------------------------------------------------------
    !  now set up splines (8 cases - four species, each real and imaginary)
    !  We have to allow for the case when there are no constituent amplitudes
    !  for the long-period tides.
    !----------------------------------------------------------------------
    !      print *, RF
    IF(NLP.NE.0) CALL SPLINE(NLP, RF, RL, ZDR, SCR)
    IF(NLP.NE.0) CALL SPLINE(NLP, RF, AIM, ZDI, SCR)
    CALL SPLINE(NDI, RF(NLP + 1), RL(NLP + 1), DR, SCR)
    CALL SPLINE(NDI, RF(NLP + 1), AIM(NLP + 1), DI, SCR)
    CALL SPLINE(NSD, RF(NLP + NDI + 1), RL(NLP + NDI + 1), SDR, SCR)
    CALL SPLINE(NSD, RF(NLP + NDI + 1), AIM(NLP + NDI + 1), SDI, SCR)
    !  Evaluate all harmonics using the interpolated admittance
    J = 1
    DO I = 1, NT
        IF(IDD(1, I).EQ.0.AND.NLP.EQ.0) GO TO 11
        CALL TDFRPH(IDD(1, I), F(J), P(J))
        !  Compute phase corrections to equilibrium tide using function EVAL
        IF(IDD(1, I).EQ.0) P(J) = P(J) + 180.
        IF(IDD(1, I).EQ.1) P(J) = P(J) + 90.
        SF = F(J)
        IF(IDD(1, I).EQ.0) RE = EVAL(SF, NLP, RF, RL, ZDR)
        IF(IDD(1, I).EQ.0) AM = EVAL(SF, NLP, RF, AIM, ZDI)
        IF(IDD(1, I).EQ.1) RE = EVAL(SF, NDI, RF(NLP + 1), RL(NLP + 1), DR)
        IF(IDD(1, I).EQ.1) AM = EVAL(SF, NDI, RF(NLP + 1), AIM(NLP + 1), DI)
        IF(IDD(1, I).EQ.2) RE = &
                EVAL(SF, NSD, RF(NLP + NDI + 1), RL(NLP + NDI + 1), SDR)
        IF(IDD(1, I).EQ.2) AM = &
                EVAL(SF, NSD, RF(NLP + NDI + 1), AIM(NLP + NDI + 1), SDI)
        !      print *, RF(NLP+NDI+1:NLP+NDI+NSD), RL(NLP+NDI+1:NLP+NDI+NSD)
        !      pause
        !      print *, RE, AM
        AMP(J) = TAMP(I) * SQRT(RE**2 + AM**2)
        P(J) = P(J) + ATAN2(AM, RE) / DTR
        IF(P(J).GT.180) P(J) = P(J) - 360.
        !         print *, P(J)
        J = J + 1
        11      CONTINUE
    ENDDO
    NOUT = J - 1
    !      open(unit=23,file="logt.log",access="append",status="old")
    !      write(23,*), NOUT
    !      close(23)
    RETURN

    !  Finished.

END

SUBROUTINE TDFRPH (IDOOD, FREQ, PHASE)
    !+
    !  - - - - - - - - - - -
    !   T D F R P H
    !  - - - - - - - - - - -
    !
    !  This routine is part of the International Earth Rotation and
    !  Reference Systems Service (IERS) Conventions software collection.
    !
    !  This subroutine returns the frequency and phase of a tidal
    !  constituent when its Doodson number is given as input.
    !
    !  In general, Class 1, 2, and 3 models represent physical effects that
    !  act on geodetic parameters while canonical models provide lower-level
    !  representations or basic computations that are used by Class 1, 2, or
    !  3 models.
    !
    !  Status:  Class 1 model
    !
    !     Class 1 models are those recommended to be used a priori in the
    !     reduction of raw space geodetic data in order to determine
    !     geodetic parameter estimates.
    !     Class 2 models are those that eliminate an observational
    !     singularity and are purely conventional in nature.
    !     Class 3 models are those that are not required as either Class
    !     1 or 2.
    !     Canonical models are accepted as is and cannot be classified as
    !     a Class 1, 2, or 3 model.
    !
    !  Given:
    !     idood       i      Doodson number of a tidal constituent
    !
    !  Returned:
    !     freq        d      Frequency of a tidal constituent
    !     phase       d      Phase of a tidal constituent (Note 1)
    !
    !  Notes:
    !
    !  1) The phases must be decreased by 90 degrees if the sum of the order
    !     and the species number is odd (as for the 2nd degree diurnals, and
    !     3rd degree low frequency and semidiurnals).
    !
    !     These phases may need further adjustment to allow for the spherical
    !     harmonic normalization used; e.g. for that used for the potential
    !     by Cartwright and Tayler, 180 degrees must be added for (species,
    !     order) = (1,2), (1,3), or (3,3).
    !
    !  Called:
    !     TOYMD     Converts year-day of year to year-month-day format
    !     LEAP      Returns true if a given year is a leap year
    !     JULDAT    Converts Gregorian date to Julian date
    !     ETUTC     Returns difference of Epheremis Time (ET) and
    !               Coordinated Universal Time (UTC)
    !
    !  Test case:
    !     given input: For June 25, 2009 0 Hr 0 Min, M2 tide
    !                  DATA IDOOD = / 2, 0, 0, 0, 0, 0 /
    !
    !     expected output: FREQ = 1.93227361605688D0
    !                      PHASE = 132.8193176853237674D0
    !
    !  References:
    !
    !     Petit, G. and Luzum, B. (eds.), IERS Conventions (2010),
    !     IERS Technical Note No. 36, BKG (2010)
    !
    !  Revisions:
    !  2009 June   15 B.E.Stetzler  Initial changes to code
    !  2009 August 19 B.E.Stetzler  Capitalized all variables for FORTRAN
    !                               77 compatibility
    !  2010 March  19 B.E.Stetzler  Provided test case
    !-----------------------------------------------------------------------

    IMPLICIT NONE
    !      SAVE ITMSAVE,D,DD
    INTEGER I, INITIAL, ITM, ITM2, ITMSAVE, JD, JULDAT, LEAP
    INTEGER*8 IDOOD
    DOUBLE PRECISION YEAR, DELTA, FREQ, PHASE, &
            D, DAYFR, DD, DJD, F1, F2, F3, F4, F5, &
            FD1, FD2, FD3, FD4, FD5, T
    DIMENSION IDOOD(6), ITM2(6), ITMSAVE(5), D(6), DD(6)

    ! Common block 'date' stores time information in Universal Time (UT)

    COMMON/DATE/ITM(5)
    !      DATA ITMSAVE/5*0/
    !------------------------------------------------------------------------
    !  Test to see if time has changed; if so, set the phases and frequencies
    !  for each of the Doodson arguments
    !------------------------------------------------------------------------
    INITIAL = 0

    !      DO I=1,5
    !        IF(ITM(I).NE.ITMSAVE(I)) INITIAL=1
    !      ENDDO

    !      IF(INITIAL.EQ.1) THEN
    !        DO I=1,5
    !           ITMSAVE(I) = ITM(I)
    !        ENDDO

    ! Convert times to Julian days (UT) then to Julian centuries from J2000.0
    !   (ET)
    CALL TOYMD(ITM, ITM2)
    JD = JULDAT(ITM2)
    DAYFR = ITM(3) / 24.0D0 + ITM(4) / 1440.0D0 + ITM(5) / 86400.0D0
    YEAR = ITM(1) + (ITM(2) + DAYFR) / (365.0D0 + LEAP(ITM(1)))
    CALL ETUTC(YEAR, DELTA)
    DJD = JD - 0.5D0 + DAYFR
    T = (DJD - 2451545.0D0 + DELTA / 86400.0D0) / 36525.0D0

    ! IERS expressions for the Delaunay arguments, in degrees

    F1 = 134.9634025100D0 + &
            T * (477198.8675605000D0 + &
                    T * (0.0088553333D0 + &
                            T * (0.0000143431D0 + &
                                    T * (-0.0000000680D0))))
    F2 = 357.5291091806D0 + &
            T * (35999.0502911389D0 + &
                    T * (-0.0001536667D0 + &
                            T * (0.0000000378D0 + &
                                    T * (-0.0000000032D0))))
    F3 = 93.2720906200D0 + &
            T * (483202.0174577222D0 + &
                    T * (-0.0035420000D0 + &
                            T * (-0.0000002881D0 + &
                                    T * (0.0000000012D0))))
    F4 = 297.8501954694D0 + &
            T * (445267.1114469445D0 + &
                    T * (-0.0017696111D0 + &
                            T * (0.0000018314D0 + &
                                    T * (-0.0000000088D0))))
    F5 = 125.0445550100D0 + &
            T * (-1934.1362619722D0 + &
                    T * (0.0020756111D0 + &
                            T * (0.0000021394D0 + &
                                    T * (-0.0000000165D0))))

    !  Convert to Doodson (Darwin) variables

    D(1) = 360.0D0 * DAYFR - F4
    D(2) = F3 + F5
    D(3) = D(2) - F4
    D(4) = D(2) - F1
    D(5) = -F5
    D(6) = D(3) - F2

    !  Find frequencies of Delauney variables (in cycles/day), and from these
    !  the same for the Doodson arguments

    FD1 = 0.0362916471D0 + 0.0000000013D0 * T
    FD2 = 0.0027377786D0
    FD3 = 0.0367481951D0 - 0.0000000005D0 * T
    FD4 = 0.0338631920D0 - 0.0000000003D0 * T
    FD5 = -0.0001470938D0 + 0.0000000003D0 * T
    DD(1) = 1.0D0 - FD4
    DD(2) = FD3 + FD5
    DD(3) = DD(2) - FD4
    DD(4) = DD(2) - FD1
    DD(5) = -FD5
    DD(6) = DD(3) - FD2
    !      ENDIF

    !  End of intialization (likely to be called only once)

    !  Compute phase and frequency of the given tidal constituent

    FREQ = 0.0D0
    PHASE = 0.0D0
    DO I = 1, 6
        FREQ = FREQ + IDOOD(I) * DD(I)
        PHASE = PHASE + IDOOD(I) * D(I)
    ENDDO

    !      print *, FREQ
    !      print *, PHASE
    !      print *,'\n'
    ! Adjust phases so that they fall in the positive range 0 to 360
    PHASE = DMOD(PHASE, 360.0D0)
    IF(PHASE.LT.0.0D0) PHASE = PHASE + 360.0D0

    RETURN

    !  Finished.

    !+----------------------------------------------------------------------
    !
    !  Copyright (C) 2008
    !  IERS Conventions Center
    !
    !  ==================================
    !  IERS Conventions Software License
    !  ==================================
    !
    !  NOTICE TO USER:
    !
    !  BY USING THIS SOFTWARE YOU ACCEPT THE FOLLOWING TERMS AND CONDITIONS
    !  WHICH APPLY TO ITS USE.
    !
    !  1. The Software is provided by the IERS Conventions Center ("the
    !     Center").
    !
    !  2. Permission is granted to anyone to use the Software for any
    !     purpose, including commercial applications, free of charge,
    !     subject to the conditions and restrictions listed below.
    !
    !  3. You (the user) may adapt the Software and its algorithms for your
    !     own purposes and you may distribute the resulting "derived work"
    !     to others, provided that the derived work complies with the
    !     following requirements:
    !
    !     a) Your work shall be clearly identified so that it cannot be
    !        mistaken for IERS Conventions software and that it has been
    !        neither distributed by nor endorsed by the Center.
    !
    !     b) Your work (including source code) must contain descriptions of
    !        how the derived work is based upon and/or differs from the
    !        original Software.
    !
    !     c) The name(s) of all modified routine(s) that you distribute
    !        shall be changed.
    !
    !     d) The origin of the IERS Conventions components of your derived
    !        work must not be misrepresented; you must not claim that you
    !        wrote the original Software.
    !
    !     e) The source code must be included for all routine(s) that you
    !        distribute.  This notice must be reproduced intact in any
    !        source distribution.
    !
    !  4. In any published work produced by the user and which includes
    !     results achieved by using the Software, you shall acknowledge
    !     that the Software was used in obtaining those results.
    !
    !  5. The Software is provided to the user "as is" and the Center makes
    !     no warranty as to its use or performance.   The Center does not
    !     and cannot warrant the performance or results which the user may
    !     obtain by using the Software.  The Center makes no warranties,
    !     express or implied, as to non-infringement of third party rights,
    !     merchantability, or fitness for any particular purpose.  In no
    !     event will the Center be liable to the user for any consequential,
    !     incidental, or special damages, including any lost profits or lost
    !     savings, even if a Center representative has been advised of such
    !     damages, or for any claim by any third party.
    !
    !  Correspondence concerning IERS Conventions software should be
    !  addressed as follows:
    !
    !                     Gerard Petit
    !     Internet email: gpetit[at]bipm.org
    !     Postal address: IERS Conventions Center
    !                     Time, frequency and gravimetry section, BIPM
    !                     Pavillon de Breteuil
    !                     92312 Sevres  FRANCE
    !
    !     or
    !
    !                     Brian Luzum
    !     Internet email: brian.luzum[at]usno.navy.mil
    !     Postal address: IERS Conventions Center
    !                     Earth Orientation Department
    !                     3450 Massachusetts Ave, NW
    !                     Washington, DC 20392
    !
    !
    !-----------------------------------------------------------------------
END

SUBROUTINE TOYMD (IT1, IT2)
    !+
    !  - - - - - - - - - - -
    !   T O Y M D
    !  - - - - - - - - - - -
    !
    !  This routine is part of the International Earth Rotation and
    !  Reference Systems Service (IERS) Conventions software collection.
    !
    !  This subroutine converts times given in it1 expressed in year and
    !  day of year to year-month-day in it2.
    !
    !  In general, Class 1, 2, and 3 models represent physical effects that
    !  act on geodetic parameters while canonical models provide lower-level
    !  representations or basic computations that are used by Class 1, 2, or
    !  3 models.
    !
    !  Status: Canonical model
    !
    !     Class 1 models are those recommended to be used a priori in the
    !     reduction of raw space geodetic data in order to determine
    !     geodetic parameter estimates.
    !     Class 2 models are those that eliminate an observational
    !     singularity and are purely conventional in nature.
    !     Class 3 models are those that are not required as either Class
    !     1 or 2.
    !     Canonical models are accepted as is and cannot be classified as a
    !     Class 1, 2, or 3 model.
    !
    !  Given:
    !     it1           i(2)      time given in year and day of year (Note 1)
    !
    !  Returned:
    !     it2           i(3)      time given in year-month-day format
    !
    !  Notes:
    !
    !  1) The time is split into a year, given as it1(1) and the day of the
    !     year, given as it1(2).
    !
    !  Called:
    !    LEAP
    !
    !  Test case:
    !    Given input:  it1(1) = 2008
    !                  it1(2) = 120
    !
    !    Expected output: it2(1) = 2008
    !                     it2(2) = 4
    !                     it2(3) = 29
    !
    !  References:
    !
    !     Petit, G. and Luzum, B. (eds.), IERS Conventions (2010),
    !     IERS Technical Note No. 36, BKG (2010)
    !
    !  Revisions:
    !  2009 April   20 B.E.Stetzler Initial standardization of subroutine
    !  2009 April   23 B.E.Stetzler Provided test case
    !  2009 August  19 B.E.Stetzler Capitalized all variables for FORTRAN
    !                               77 compatibility
    !-----------------------------------------------------------------------

    IMPLICIT NONE
    INTEGER IDN, IT1, IT2, JJ, M, MON, LEAP
    !      DIMENSION IT1(*),IT2(*)
    DIMENSION IT1(2), IT2(3)

    IDN(M) = MOD((367 * (M - 2 - 12 * ((M - 14) / 12))) / 12 + 29, 365)
    MON(JJ, M) = (12 * (JJ - 29 - M)) / 367 + 2 + (JJ - 200) / 169
    IT2(1) = IT1(1)
    IT2(2) = MON(IT1(2), LEAP(IT1(1)))
    IT2(3) = IT1(2) - IDN(IT2(2)) - LEAP(IT2(1)) * ((9 + IT2(2)) / 12)
    RETURN

    ! Finished.

    !+----------------------------------------------------------------------
    !
    !  Copyright (C) 2008
    !  IERS Conventions Center
    !
    !  ==================================
    !  IERS Conventions Software License
    !  ==================================
    !
    !  NOTICE TO USER:
    !
    !  BY USING THIS SOFTWARE YOU ACCEPT THE FOLLOWING TERMS AND CONDITIONS
    !  WHICH APPLY TO ITS USE.
    !
    !  1. The Software is provided by the IERS Conventions Center ("the
    !     Center").
    !
    !  2. Permission is granted to anyone to use the Software for any
    !     purpose, including commercial applications, free of charge,
    !     subject to the conditions and restrictions listed below.
    !
    !  3. You (the user) may adapt the Software and its algorithms for your
    !     own purposes and you may distribute the resulting "derived work"
    !     to others, provided that the derived work complies with the
    !     following requirements:
    !
    !     a) Your work shall be clearly identified so that it cannot be
    !        mistaken for IERS Conventions software and that it has been
    !        neither distributed by nor endorsed by the Center.
    !
    !     b) Your work (including source code) must contain descriptions of
    !        how the derived work is based upon and/or differs from the
    !        original Software.
    !
    !     c) The name(s) of all modified routine(s) that you distribute
    !        shall be changed.
    !
    !     d) The origin of the IERS Conventions components of your derived
    !        work must not be misrepresented; you must not claim that you
    !        wrote the original Software.
    !
    !     e) The source code must be included for all routine(s) that you
    !        distribute.  This notice must be reproduced intact in any
    !        source distribution.
    !
    !  4. In any published work produced by the user and which includes
    !     results achieved by using the Software, you shall acknowledge
    !     that the Software was used in obtaining those results.
    !
    !  5. The Software is provided to the user "as is" and the Center makes
    !     no warranty as to its use or performance.   The Center does not
    !     and cannot warrant the performance or results which the user may
    !     obtain by using the Software.  The Center makes no warranties,
    !     express or implied, as to non-infringement of third party rights,
    !     merchantability, or fitness for any particular purpose.  In no
    !     event will the Center be liable to the user for any consequential,
    !     incidental, or special damages, including any lost profits or lost
    !     savings, even if a Center representative has been advised of such
    !     damages, or for any claim by any third party.
    !
    !  Correspondence concerning IERS Conventions software should be
    !  addressed as follows:
    !
    !                     Gerard Petit
    !     Internet email: gpetit[at]bipm.org
    !     Postal address: IERS Conventions Center
    !                     Time, frequency and gravimetry section, BIPM
    !                     Pavillon de Breteuil
    !                     92312 Sevres  FRANCE
    !
    !     or
    !
    !                     Brian Luzum
    !     Internet email: brian.luzum[at]usno.navy.mil
    !     Postal address: IERS Conventions Center
    !                     Earth Orientation Department
    !                     3450 Massachusetts Ave, NW
    !                     Washington, DC 20392
    !
    !
    !-----------------------------------------------------------------------
END

SUBROUTINE SPLINE (NN, X, U, S, A)
    !+
    !  - - - - - - - - -
    !   S P L I N E
    !  - - - - - - - - -
    !
    !  This routine is part of the International Earth Rotation and
    !  Reference Systems Service (IERS) Conventions software collection.
    !
    !  The purpose of the subroutine is to find an array s for the spline
    !  interpolator function EVAL.
    !
    !  In general, Class 1, 2, and 3 models represent physical effects that
    !  act on geodetic parameters while canonical models provide lower-level
    !  representations or basic computations that are used by Class 1, 2, or
    !  3 models.
    !
    !  Status: Canonical model
    !
    !     Class 1 models are those recommended to be used a priori in the
    !     reduction of raw space geodetic data in order to determine
    !     geodetic parameter estimates.
    !     Class 2 models are those that eliminate an observational
    !     singularity and are purely conventional in nature.
    !     Class 3 models are those that are not required as either Class
    !     1 or 2.
    !     Canonical models are accepted as is and cannot be classified as a
    !     Class 1, 2, or 3 model.
    !
    !  Given: This is a support routine of the main program HARDISP.F.
    !     nn             i      number of data points supplied, which may be
    !                           negative (Note 1)
    !     x              d      array containing x-coordinates where function
    !                           is sampled (Note 2)
    !     u              d      array containing sample values that are to be
    !                           interpolated
    !     a              d      working space array of dimension at least nn
    !
    !  Returned:
    !     s              d      output array of 2nd derivative at sample points
    !
    !  Notes:
    !
    !  1) If the user wishes to force the derivatives at the ends of the series
    !     to assume specified values, he or she should put du(1)/dx and du(n)/dx
    !     in the variables s1 and s2 and call the subroutine with nn = -(number
    !     of terms in the series).  Normally a parabola is fitted through the
    !     1st and last 3 points to find the slopes.  If less than 4 points are
    !     supplied, straight lines are fitted.
    !
    !  2) The sequence xx(1), xx(2), ... xx(nn) must be strictly increasing.
    !
    !  Called:
    !     None
    !
    !  Test case:
    !     Not provided for this subroutine.
    !
    !  References:
    !
    !     Petit, G. and Luzum, B. (eds.), IERS Conventions (2010),
    !     IERS Technical Note No. 36, BKG (2010)
    !
    !  Revisions:
    !  2009 June   08 B.E.Stetzler    Added header and copyright
    !  2009 August 19 B.E.Stetzler    Capitalized all variables for FORTRAN
    !                                 77 compatibility
    !  2009 August 26 B.E.Stetzler    Used IMPLICIT NONE and defined all variables
    !-----------------------------------------------------------------------

    IMPLICIT NONE
    INTEGER I, J, N, N1, NN, NMAX
    PARAMETER (NMAX = 20)
    REAL A, C, Q, Q1, QN, S, U, X, U1, U2, X1, X2
    DIMENSION X(NMAX), U(NMAX), S(NMAX), A(NMAX)

    Q(U1, X1, U2, X2) = (U1 / X1**2 - U2 / X2**2) / (1.0 / X1 - 1.0 / X2)

    N = IABS(NN)

    IF (N.LE.3) THEN

        !  series too short for cubic spline - use straight lines.
        DO I = 1, N
            S(I) = 0.0
        ENDDO
        RETURN
    ENDIF

    Q1 = Q(U(2) - U(1), X(2) - X(1), U(3) - U(1), X(3) - X(1))
    QN = Q(U(N - 1) - U(N), X(N - 1) - X(N), U(N - 2) - U(N), X(N - 2) - X(N))

    IF (NN.LE.0) THEN
        Q1 = S(1)
        QN = S(2)
    ENDIF

    S(1) = 6.0 * ((U(2) - U(1)) / (X(2) - X(1)) - Q1)
    N1 = N - 1

    DO I = 2, N1
        S(I) = (U(I - 1) / (X(I) - X(I - 1)) - U(I) * (1.0 / (X(I) - X(I - 1))&
                + 1.0 / (X(I + 1) - X(I))) + U(I + 1) / (X(I + 1) - X(I))) * 6.0
    ENDDO

    S(N) = 6.0 * (QN + (U(N1) - U(N)) / (X(N) - X(N1)))
    A(1) = 2.0 * (X(2) - X(1))
    A(2) = 1.5 * (X(2) - X(1)) + 2.0 * (X(3) - X(2))
    S(2) = S(2) - 0.5 * S(1)

    DO I = 3, N1
        C = (X(I) - X(I - 1)) / A(I - 1)
        A(I) = 2.0 * (X(I + 1) - X(I - 1)) - C * (X(I) - X(I - 1))
        S(I) = S(I) - C * S(I - 1)
    ENDDO

    C = (X(N) - X(N1)) / A(N1)
    A(N) = (2.0 - C) * (X(N) - X(N1))
    S(N) = S(N) - C * S(N1)

    !  Back substitute
    S(N) = S(N) / A(N)

    DO J = 1, N1
        I = N - J
        S(I) = (S(I) - (X(I + 1) - X(I)) * S(I + 1)) / A(I)
    ENDDO
    RETURN

    ! Finished.

    !+----------------------------------------------------------------------
    !
    !  Copyright (C) 2008
    !  IERS Conventions Center
    !
    !  ==================================
    !  IERS Conventions Software License
    !  ==================================
    !
    !  NOTICE TO USER:
    !
    !  BY USING THIS SOFTWARE YOU ACCEPT THE FOLLOWING TERMS AND CONDITIONS
    !  WHICH APPLY TO ITS USE.
    !
    !  1. The Software is provided by the IERS Conventions Center ("the
    !     Center").
    !
    !  2. Permission is granted to anyone to use the Software for any
    !     purpose, including commercial applications, free of charge,
    !     subject to the conditions and restrictions listed below.
    !
    !  3. You (the user) may adapt the Software and its algorithms for your
    !     own purposes and you may distribute the resulting "derived work"
    !     to others, provided that the derived work complies with the
    !     following requirements:
    !
    !     a) Your work shall be clearly identified so that it cannot be
    !        mistaken for IERS Conventions software and that it has been
    !        neither distributed by nor endorsed by the Center.
    !
    !     b) Your work (including source code) must contain descriptions of
    !        how the derived work is based upon and/or differs from the
    !        original Software.
    !
    !     c) The name(s) of all modified routine(s) that you distribute
    !        shall be changed.
    !
    !     d) The origin of the IERS Conventions components of your derived
    !        work must not be misrepresented; you must not claim that you
    !        wrote the original Software.
    !
    !     e) The source code must be included for all routine(s) that you
    !        distribute.  This notice must be reproduced intact in any
    !        source distribution.
    !
    !  4. In any published work produced by the user and which includes
    !     results achieved by using the Software, you shall acknowledge
    !     that the Software was used in obtaining those results.
    !
    !  5. The Software is provided to the user "as is" and the Center makes
    !     no warranty as to its use or performance.   The Center does not
    !     and cannot warrant the performance or results which the user may
    !     obtain by using the Software.  The Center makes no warranties,
    !     express or implied, as to non-infringement of third party rights,
    !     merchantability, or fitness for any particular purpose.  In no
    !     event will the Center be liable to the user for any consequential,
    !     incidental, or special damages, including any lost profits or lost
    !     savings, even if a Center representative has been advised of such
    !     damages, or for any claim by any third party.
    !
    !  Correspondence concerning IERS Conventions software should be
    !  addressed as follows:
    !
    !                     Gerard Petit
    !     Internet email: gpetit[at]bipm.org
    !     Postal address: IERS Conventions Center
    !                     Time, frequency and gravimetry section, BIPM
    !                     Pavillon de Breteuil
    !                     92312 Sevres  FRANCE
    !
    !     or
    !
    !                     Brian Luzum
    !     Internet email: brian.luzum[at]usno.navy.mil
    !     Postal address: IERS Conventions Center
    !                     Earth Orientation Department
    !                     3450 Massachusetts Ave, NW
    !                     Washington, DC 20392
    !
    !
    !-----------------------------------------------------------------------
END

SUBROUTINE SHELLS (X, K, N)
    !+
    !  - - - - - - - - -
    !   S H E L L S
    !  - - - - - - - - -
    !
    !  This routine is part of the International Earth Rotation and
    !  Reference Systems Service (IERS) Conventions software collection.
    !
    !  The subroutine sorts an array x, of length n, sorting upward,
    !  and returns an array k which may be used to key another array
    !  to the sorted pattern (i.e., if we had an array f to which x
    !  corresponded before sorting, then after calling SHELLS,
    !  f(k(1)) will be the element of f corresponding to the
    !  smallest x, f(k(2)) the next smallest, and so on).
    !
    !  In general, Class 1, 2, and 3 models represent physical effects that
    !  act on geodetic parameters while canonical models provide lower-level
    !  representations or basic computations that are used by Class 1, 2, or
    !  3 models.
    !
    !  Status: Canonical model
    !
    !     Class 1 models are those recommended to be used a priori in the
    !     reduction of raw space geodetic data in order to determine
    !     geodetic parameter estimates.
    !     Class 2 models are those that eliminate an observational
    !     singularity and are purely conventional in nature.
    !     Class 3 models are those that are not required as either Class
    !     1 or 2.
    !     Canonical models are accepted as is and cannot be classified as a
    !     Class 1, 2, or 3 model.
    !
    !  Given:
    !     x              d      array to be sorted (Note 1)
    !     n              i      length of the input array x
    !
    !  Returned:
    !     k              i      sorted array that may be used to key another
    !                           array
    !  Notes:
    !
    !  1) See the subroutine ADMINT.F header comments for detailed information.
    !
    !  Called:
    !     None
    !
    !  Test case:
    !     Not provided for this subroutine.
    !
    !  References:
    !
    !     Petit, G. and Luzum, B. (eds.), IERS Conventions (2010),
    !     IERS Technical Note No. 36, BKG (2010)
    !
    !  Revisions:
    !  1982 December 29              Revised so that array k is sorted in turn
    !
    !  2009 June   05 B.E. Stetzler    Added header and copyright
    !  2009 August 19 B.E. Stetzler    Capitalized all variables for FORTRAN
    !                                  77 compatibility
    !-----------------------------------------------------------------------

    IMPLICIT NONE

    INTEGER I, IGAP, IEX, IK, IMAX, IPL, J, K, L, N
    REAL SV, X
    DIMENSION X(N), K(N)

    IGAP = N

    DO 1 I = 1, N
    1    K(I) = I
    5    IF(IGAP.LE.1) GO TO 25

    IGAP = IGAP / 2
    IMAX = N - IGAP
    10   IEX = 0
    DO 20 I = 1, IMAX
        IPL = I + IGAP
        IF(X(I).LE.X(IPL)) GO TO 20
        SV = X(I)
        IK = K(I)
        X(I) = X(IPL)
        K(I) = K(IPL)
        X(IPL) = SV
        K(IPL) = IK
        IEX = IEX + 1
    20   CONTINUE

    IF(IEX.GT.0) GO TO 10
    GO TO 5

    !  Now sort k's (for identical values of x, if any)

    25   J = 1
    30   IF(J.GE.N) RETURN
    IF(X(J).EQ.X(J + 1)) GO TO 33
    J = J + 1
    GO TO 30
    !  Have at least two x's with the same value. See how long this is true
    33   L = J
    35   IF(X(L).NE.X(L + 1)) GO TO 38
    L = L + 1
    IF(L.LT.N) GO TO 35
    !  j and l are the indices within which x(i) does not change - sort k
    38   IGAP = L - J + 1
    40   IF(IGAP.LE.1) J = L + 1
    IF(IGAP.LE.1) GO TO 30

    IGAP = IGAP / 2
    IMAX = L - J + 1 - IGAP
    45   IEX = 0

    DO 50 I = 1, IMAX
        IPL = I + IGAP + J - 1
        IF(K(I + J - 1).LE.K(IPL)) GO TO 50
        IK = K(I + J - 1)
        K(I + J - 1) = K(IPL)
        K(IPL) = IK
        IEX = IEX + 1
    50   CONTINUE
    IF(IEX.GT.0) GO TO 45
    GO TO 40

    ! Finished.

    !+----------------------------------------------------------------------
    !
    !  Copyright (C) 2008
    !  IERS Conventions Center
    !
    !  ==================================
    !  IERS Conventions Software License
    !  ==================================
    !
    !  NOTICE TO USER:
    !
    !  BY USING THIS SOFTWARE YOU ACCEPT THE FOLLOWING TERMS AND CONDITIONS
    !  WHICH APPLY TO ITS USE.
    !
    !  1. The Software is provided by the IERS Conventions Center ("the
    !     Center").
    !
    !  2. Permission is granted to anyone to use the Software for any
    !     purpose, including commercial applications, free of charge,
    !     subject to the conditions and restrictions listed below.
    !
    !  3. You (the user) may adapt the Software and its algorithms for your
    !     own purposes and you may distribute the resulting "derived work"
    !     to others, provided that the derived work complies with the
    !     following requirements:
    !
    !     a) Your work shall be clearly identified so that it cannot be
    !        mistaken for IERS Conventions software and that it has been
    !        neither distributed by nor endorsed by the Center.
    !
    !     b) Your work (including source code) must contain descriptions of
    !        how the derived work is based upon and/or differs from the
    !        original Software.
    !
    !     c) The name(s) of all modified routine(s) that you distribute
    !        shall be changed.
    !
    !     d) The origin of the IERS Conventions components of your derived
    !        work must not be misrepresented; you must not claim that you
    !        wrote the original Software.
    !
    !     e) The source code must be included for all routine(s) that you
    !        distribute.  This notice must be reproduced intact in any
    !        source distribution.
    !
    !  4. In any published work produced by the user and which includes
    !     results achieved by using the Software, you shall acknowledge
    !     that the Software was used in obtaining those results.
    !
    !  5. The Software is provided to the user "as is" and the Center makes
    !     no warranty as to its use or performance.   The Center does not
    !     and cannot warrant the performance or results which the user may
    !     obtain by using the Software.  The Center makes no warranties,
    !     express or implied, as to non-infringement of third party rights,
    !     merchantability, or fitness for any particular purpose.  In no
    !     event will the Center be liable to the user for any consequential,
    !     incidental, or special damages, including any lost profits or lost
    !     savings, even if a Center representative has been advised of such
    !     damages, or for any claim by any third party.
    !
    !  Correspondence concerning IERS Conventions software should be
    !  addressed as follows:
    !
    !                     Gerard Petit
    !     Internet email: gpetit[at]bipm.org
    !     Postal address: IERS Conventions Center
    !                     Time, frequency and gravimetry section, BIPM
    !                     Pavillon de Breteuil
    !                     92312 Sevres  FRANCE
    !
    !     or
    !
    !                     Brian Luzum
    !     Internet email: brian.luzum[at]usno.navy.mil
    !     Postal address: IERS Conventions Center
    !                     Earth Orientation Department
    !                     3450 Massachusetts Ave, NW
    !                     Washington, DC 20392
    !
    !
    !-----------------------------------------------------------------------
END

INTEGER FUNCTION MDAY (IY, M)
    !+
    !  - - - - - - - - - - -
    !   M D A Y
    !  - - - - - - - - - - -
    !
    !  This routine is part of the International Earth Rotation and
    !  Reference Systems Service (IERS) Conventions software collection.
    !
    !  This function finds the day number of days before start of month m,
    !  of year iy, in Gregorian intercalation.
    !
    !  In general, Class 1, 2, and 3 models represent physical effects that
    !  act on geodetic parameters while canonical models provide lower-level
    !  representations or basic computations that are used by Class 1, 2, or
    !  3 models.
    !
    !  Status: Canonical model
    !
    !     Class 1 models are those recommended to be used a priori in the
    !     reduction of raw space geodetic data in order to determine
    !     geodetic parameter estimates.
    !     Class 2 models are those that eliminate an observational
    !     singularity and are purely conventional in nature.
    !     Class 3 models are those that are not required as either Class
    !     1 or 2.
    !     Canonical models are accepted as is and cannot be classified as a
    !     Class 1, 2, or 3 model.
    !
    !  Given:
    !     iy           i      a year
    !     m            i      a month
    !
    !  Returned:
    !     mday         i      day number of day before start of a month
    !
    !  Notes:
    !
    !  1)  This function needs to test for a leap year.
    !
    !  Called:
    !     None
    !
    !  Test case:  This is a support function of the main program HARDISP.F.
    !     given input: iy = 2009
    !                   m = 5
    !     expected output: mday = 120
    !
    !  References:
    !
    !     Petit, G. and Luzum, B. (eds.), IERS Conventions (2010),
    !     IERS Technical Note No. 36, BKG (2010)
    !
    !  Revisions:
    !  2009 April 22 B.E. Stetzler Initial standardization of function
    !                              and provided a test case
    !  2009 July  29 B.E. Stetzler Capitalized all variables for FORTRAN 77
    !                              compatibility
    !-----------------------------------------------------------------------

    IMPLICIT NONE

    INTEGER IY, LEAP, M

    LEAP = 1 - (MOD(IY, 4) + 3) / 4
    IF(MOD(IY, 100).EQ.0.AND.MOD(IY, 400).NE.0) LEAP = 0
    MDAY = MOD((367 * (M - 2 - 12 * ((M - 14) / 12))) / 12 + 29, 365) + LEAP * ((9 + M) / 12)

    RETURN

    ! Finished.

    !+----------------------------------------------------------------------
    !
    !  Copyright (C) 2008
    !  IERS Conventions Center
    !
    !  ==================================
    !  IERS Conventions Software License
    !  ==================================
    !
    !  NOTICE TO USER:
    !
    !  BY USING THIS SOFTWARE YOU ACCEPT THE FOLLOWING TERMS AND CONDITIONS
    !  WHICH APPLY TO ITS USE.
    !
    !  1. The Software is provided by the IERS Conventions Center ("the
    !     Center").
    !
    !  2. Permission is granted to anyone to use the Software for any
    !     purpose, including commercial applications, free of charge,
    !     subject to the conditions and restrictions listed below.
    !
    !  3. You (the user) may adapt the Software and its algorithms for your
    !     own purposes and you may distribute the resulting "derived work"
    !     to others, provided that the derived work complies with the
    !     following requirements:
    !
    !     a) Your work shall be clearly identified so that it cannot be
    !        mistaken for IERS Conventions software and that it has been
    !        neither distributed by nor endorsed by the Center.
    !
    !     b) Your work (including source code) must contain descriptions of
    !        how the derived work is based upon and/or differs from the
    !        original Software.
    !
    !     c) The name(s) of all modified routine(s) that you distribute
    !        shall be changed.
    !
    !     d) The origin of the IERS Conventions components of your derived
    !        work must not be misrepresented; you must not claim that you
    !        wrote the original Software.
    !
    !     e) The source code must be included for all routine(s) that you
    !        distribute.  This notice must be reproduced intact in any
    !        source distribution.
    !
    !  4. In any published work produced by the user and which includes
    !     results achieved by using the Software, you shall acknowledge
    !     that the Software was used in obtaining those results.
    !
    !  5. The Software is provided to the user "as is" and the Center makes
    !     no warranty as to its use or performance.   The Center does not
    !     and cannot warrant the performance or results which the user may
    !     obtain by using the Software.  The Center makes no warranties,
    !     express or implied, as to non-infringement of third party rights,
    !     merchantability, or fitness for any particular purpose.  In no
    !     event will the Center be liable to the user for any consequential,
    !     incidental, or special damages, including any lost profits or lost
    !     savings, even if a Center representative has been advised of such
    !     damages, or for any claim by any third party.
    !
    !  Correspondence concerning IERS Conventions software should be
    !  addressed as follows:
    !
    !                     Gerard Petit
    !     Internet email: gpetit[at]bipm.org
    !     Postal address: IERS Conventions Center
    !                     Time, frequency and gravimetry section, BIPM
    !                     Pavillon de Breteuil
    !                     92312 Sevres  FRANCE
    !
    !     or
    !
    !                     Brian Luzum
    !     Internet email: brian.luzum[at]usno.navy.mil
    !     Postal address: IERS Conventions Center
    !                     Earth Orientation Department
    !                     3450 Massachusetts Ave, NW
    !                     Washington, DC 20392
    !
    !
    !-----------------------------------------------------------------------
END

INTEGER FUNCTION LEAP (IY)
    !+
    !  - - - - - - - - - - -
    !   L E A P
    !  - - - - - - - - - - -
    !
    !  This routine is part of the International Earth Rotation and
    !  Reference Systems Service (IERS) Conventions software collection.
    !
    !  This function determines whether a given integer year is a leap
    !  year.
    !
    !  In general, Class 1, 2, and 3 models represent physical effects that
    !  act on geodetic parameters while canonical models provide lower-level
    !  representations or basic computations that are used by Class 1, 2, or
    !  3 models.
    !
    !  Status: Canonical model
    !
    !     Class 1 models are those recommended to be used a priori in the
    !     reduction of raw space geodetic data in order to determine
    !     geodetic parameter estimates.
    !     Class 2 models are those that eliminate an observational
    !     singularity and are purely conventional in nature.
    !     Class 3 models are those that are not required as either Class
    !     1 or 2.
    !     Canonical models are accepted as is and cannot be classified as a
    !     Class 1, 2, or 3 model.
    !
    !  Given:
    !     iy           i      a year (Note 1)
    !
    !  Returned:
    !     0            i      if year is not a leap year
    !     1            i      if year is a leap year
    !
    !  Notes:
    !
    !  1) The year is a Gregorian year.
    !
    !  Called:
    !     None
    !
    !  Test case:  This is a support function of the main program HARDISP.F.
    !     given input: IY = 2009
    !
    !     expected output: 0
    !
    !  References:
    !
    !     Petit, G. and Luzum, B. (eds.), IERS Conventions (2010),
    !     IERS Technical Note No. 36, BKG (2010)
    !
    !  Revisions:
    !  2009 April  20 B.E.Stetzler  Initial standardization of function
    !                               and provided a test case
    !  2009 August 19 B.E.Stetzler  Capitalized all variables for FORTRAN
    !                               77 compatibility
    !-----------------------------------------------------------------------

    IMPLICIT NONE
    INTEGER IY

    LEAP = 1 - (MOD(IY, 4) + 3) / 4

    IF(MOD(IY, 100).EQ.0.AND.MOD(IY, 400).NE.0) LEAP = 0

    RETURN

    ! Finished.

    !+----------------------------------------------------------------------
    !
    !  Copyright (C) 2008
    !  IERS Conventions Center
    !
    !  ==================================
    !  IERS Conventions Software License
    !  ==================================
    !
    !  NOTICE TO USER:
    !
    !  BY USING THIS SOFTWARE YOU ACCEPT THE FOLLOWING TERMS AND CONDITIONS
    !  WHICH APPLY TO ITS USE.
    !
    !  1. The Software is provided by the IERS Conventions Center ("the
    !     Center").
    !
    !  2. Permission is granted to anyone to use the Software for any
    !     purpose, including commercial applications, free of charge,
    !     subject to the conditions and restrictions listed below.
    !
    !  3. You (the user) may adapt the Software and its algorithms for your
    !     own purposes and you may distribute the resulting "derived work"
    !     to others, provided that the derived work complies with the
    !     following requirements:
    !
    !     a) Your work shall be clearly identified so that it cannot be
    !        mistaken for IERS Conventions software and that it has been
    !        neither distributed by nor endorsed by the Center.
    !
    !     b) Your work (including source code) must contain descriptions of
    !        how the derived work is based upon and/or differs from the
    !        original Software.
    !
    !     c) The name(s) of all modified routine(s) that you distribute
    !        shall be changed.
    !
    !     d) The origin of the IERS Conventions components of your derived
    !        work must not be misrepresented; you must not claim that you
    !        wrote the original Software.
    !
    !     e) The source code must be included for all routine(s) that you
    !        distribute.  This notice must be reproduced intact in any
    !        source distribution.
    !
    !  4. In any published work produced by the user and which includes
    !     results achieved by using the Software, you shall acknowledge
    !     that the Software was used in obtaining those results.
    !
    !  5. The Software is provided to the user "as is" and the Center makes
    !     no warranty as to its use or performance.   The Center does not
    !     and cannot warrant the performance or results which the user may
    !     obtain by using the Software.  The Center makes no warranties,
    !     express or implied, as to non-infringement of third party rights,
    !     merchantability, or fitness for any particular purpose.  In no
    !     event will the Center be liable to the user for any consequential,
    !     incidental, or special damages, including any lost profits or lost
    !     savings, even if a Center representative has been advised of such
    !     damages, or for any claim by any third party.
    !
    !  Correspondence concerning IERS Conventions software should be
    !  addressed as follows:
    !
    !                     Gerard Petit
    !     Internet email: gpetit[at]bipm.org
    !     Postal address: IERS Conventions Center
    !                     Time, frequency and gravimetry section, BIPM
    !                     Pavillon de Breteuil
    !                     92312 Sevres  FRANCE
    !
    !     or
    !
    !                     Brian Luzum
    !     Internet email: brian.luzum[at]usno.navy.mil
    !     Postal address: IERS Conventions Center
    !                     Earth Orientation Department
    !                     3450 Massachusetts Ave, NW
    !                     Washington, DC 20392
    !
    !
    !-----------------------------------------------------------------------
END

INTEGER FUNCTION JULDAT (IT)
    !+
    !  - - - - - - - - - - -
    !   J U L D A T
    !  - - - - - - - - - - -
    !
    !  This function is part of the International Earth Rotation and
    !  Reference Systems Service (IERS) Conventions software collection.
    !
    !  This function converts a Gregorian date to a Julian date.
    !
    !  In general, Class 1, 2, and 3 models represent physical effects that
    !  act on geodetic parameters while canonical models provide lower-level
    !  representations or basic computations that are used by Class 1, 2, or
    !  3 models.
    !
    !  Status: Canonical model
    !
    !     Class 1 models are those recommended to be used a priori in the
    !     reduction of raw space geodetic data in order to determine
    !     geodetic parameter estimates.
    !     Class 2 models are those that eliminate an observational
    !     singularity and are purely conventional in nature.
    !     Class 3 models are those that are not required as either Class
    !     1 or 2.
    !     Canonical models are accepted as is and cannot be classified as a
    !     Class 1, 2, or 3 model.
    !
    !  Given:
    !     it           i      a Gregorian date (Note 1)
    !
    !  Returned:
    !     juldat       i      a Julian date (Note 2)
    !
    !  Notes:
    !
    !  1)  The format of the Gregorian date should be yyyy-mm-dd.
    !  2)  The date is valid for all positive values.
    !
    !  Called:
    !     None
    !
    !  Test case:  This is a support routine of the main program HARDISP.F.
    !     given input: it(1) = 2008
    !                  it(2) = 12
    !                  it(3) = 12
    !     expected output: juldat = 2454813
    !
    !  References:
    !
    !     Explanatory Supplement American Ephemeris & Nautical Almanac
    !     (cf Comm CACM, 11, 657 (1968) and 15, 918 (1972)), p. 604
    !
    !     Petit, G. and Luzum, B. (eds.), IERS Conventions (2010),
    !     IERS Technical Note No. 36, BKG (2010)
    !
    !  Revisions:
    !  2009 April  22 B.E.Stetzler  Initial standardization of function
    !                               and provided a test case
    !  2009 August 19 B.E.Stetzler  Capitalized all variables for FORTRAN
    !                               77 compatibility
    !-----------------------------------------------------------------------

    IMPLICIT NONE

    INTEGER IT
    DIMENSION IT(*)

    JULDAT = (1461 * (IT(1) + 4800 + (IT(2) - 14) / 12)) / 4&
            + (367 * (IT(2) - 2 - 12 * ((IT(2) - 14) / 12))) / 12&
            - (3 * ((IT(1) + 4900 + (IT(2) - 14) / 12) / 100)) / 4 + IT(3) - 32075

    RETURN

    ! Finished.

    !+----------------------------------------------------------------------
    !
    !  Copyright (C) 2008
    !  IERS Conventions Center
    !
    !  ==================================
    !  IERS Conventions Software License
    !  ==================================
    !
    !  NOTICE TO USER:
    !
    !  BY USING THIS SOFTWARE YOU ACCEPT THE FOLLOWING TERMS AND CONDITIONS
    !  WHICH APPLY TO ITS USE.
    !
    !  1. The Software is provided by the IERS Conventions Center ("the
    !     Center").
    !
    !  2. Permission is granted to anyone to use the Software for any
    !     purpose, including commercial applications, free of charge,
    !     subject to the conditions and restrictions listed below.
    !
    !  3. You (the user) may adapt the Software and its algorithms for your
    !     own purposes and you may distribute the resulting "derived work"
    !     to others, provided that the derived work complies with the
    !     following requirements:
    !
    !     a) Your work shall be clearly identified so that it cannot be
    !        mistaken for IERS Conventions software and that it has been
    !        neither distributed by nor endorsed by the Center.
    !
    !     b) Your work (including source code) must contain descriptions of
    !        how the derived work is based upon and/or differs from the
    !        original Software.
    !
    !     c) The name(s) of all modified routine(s) that you distribute
    !        shall be changed.
    !
    !     d) The origin of the IERS Conventions components of your derived
    !        work must not be misrepresented; you must not claim that you
    !        wrote the original Software.
    !
    !     e) The source code must be included for all routine(s) that you
    !        distribute.  This notice must be reproduced intact in any
    !        source distribution.
    !
    !  4. In any published work produced by the user and which includes
    !     results achieved by using the Software, you shall acknowledge
    !     that the Software was used in obtaining those results.
    !
    !  5. The Software is provided to the user "as is" and the Center makes
    !     no warranty as to its use or performance.   The Center does not
    !     and cannot warrant the performance or results which the user may
    !     obtain by using the Software.  The Center makes no warranties,
    !     express or implied, as to non-infringement of third party rights,
    !     merchantability, or fitness for any particular purpose.  In no
    !     event will the Center be liable to the user for any consequential,
    !     incidental, or special damages, including any lost profits or lost
    !     savings, even if a Center representative has been advised of such
    !     damages, or for any claim by any third party.
    !
    !  Correspondence concerning IERS Conventions software should be
    !  addressed as follows:
    !
    !                     Gerard Petit
    !     Internet email: gpetit[at]bipm.org
    !     Postal address: IERS Conventions Center
    !                     Time, frequency and gravimetry section, BIPM
    !                     Pavillon de Breteuil
    !                     92312 Sevres  FRANCE
    !
    !     or
    !
    !                     Brian Luzum
    !     Internet email: brian.luzum[at]usno.navy.mil
    !     Postal address: IERS Conventions Center
    !                     Earth Orientation Department
    !                     3450 Massachusetts Ave, NW
    !                     Washington, DC 20392
    !
    !
    !-----------------------------------------------------------------------
END

REAL FUNCTION EVAL (Y, NN, X, U, S)
    !+
    !  - - - - - - - - - - -
    !   E V A L
    !  - - - - - - - - - - -
    !
    !  This routine is part of the International Earth Rotation and
    !  Reference Systems Service (IERS) Conventions software collection.
    !
    !  This function performs cubic spline interpolation of a given function
    !  sampled at unequally spaced intervals.  The subroutine SPLINE needs
    !  to be called beforehand to set up the array s.
    !
    !  In general, Class 1, 2, and 3 models represent physical effects that
    !  act on geodetic parameters while canonical models provide lower-level
    !  representations or basic computations that are used by Class 1, 2, or
    !  3 models.
    !
    !  Status: Canonical model
    !
    !     Class 1 models are those recommended to be used a priori in the
    !     reduction of raw space geodetic data in order to determine
    !     geodetic parameter estimates.
    !     Class 2 models are those that eliminate an observational
    !     singularity and are purely conventional in nature.
    !     Class 3 models are those that are not required as either Class
    !     1 or 2.
    !     Canonical models are accepted as is and cannot be classified as a
    !     Class 1, 2, or 3 model.
    !
    !  Given:
    !     y            d     the coordinate at which a function value is
    !                        desired (Note 1)
    !     nn           i     number of samples of the original function
    !     x            d     array containing sample coordinates x(1),x(2),...
    !                        x(nn) (Note 2)
    !     s            d     array containing the 2nd derivatives at the sample
    !                        points (Note 3)
    !
    !  Returned:
    !     u            d     array containing samples of a function at the
    !                        coordinates x(1),x(2),...x(nn)
    !
    !  Notes:
    !
    !  1) If y falls outside the range (x(1),x(nn)), the value at the nearest
    !     endpoint of the series is used.
    !
    !  2) The sequence x(1),x(2),...x(nn) must be strictly increasing.
    !
    !  3) This array is found by the subroutine SPLINE, which must be called
    !     once before beginning this interpolation.
    !
    !  Called:
    !     None
    !
    !  Test case:
    !
    !  Not provided for this function.  This is a support routine of the main
    !  program HARDISP.F.
    !
    !  References:
    !
    !     Petit, G. and Luzum, B. (eds.), IERS Conventions (2010),
    !     IERS Technical Note No. 36, BKG (2010)
    !
    !  Revisions:
    !  2009 June   03 B.E.Stetzler Initial standardization of function
    !  2009 August 19 B.E.Stetzler Capitalized all variables for FORTRAN 77
    !                               compatibility
    !-----------------------------------------------------------------------

    IMPLICIT NONE
    INTEGER K, K1, K2, NN
    REAL DELI, DK, DY, DY1, F1, F2, F3, FF1, FF2, S, U, X, Y
    DIMENSION X(*), U(*), S(*)

    NN = IABS(NN)

    !     If y is out of range, substitute endpoint values

    IF (Y.LE.X(1)) THEN
        EVAL = U(1)
        RETURN
    ENDIF

    IF (Y.GE.X(NN)) THEN
        EVAL = U(NN)
        RETURN
    ENDIF

    !    Locate interval (x(k1),x(k2)) which contains y
    DO 100 K = 2, NN
        IF(X(K - 1).LT.Y.AND.X(K).GE.Y) THEN
            K1 = K - 1
            K2 = K
        ENDIF
    100   CONTINUE

    !    Evaluate and then interpolate
    DY = X(K2) - Y
    DY1 = Y - X(K1)
    DK = X(K2) - X(K1)
    DELI = 1.0D0 / (6.0D0 * DK)
    FF1 = S(K1) * DY * DY * DY
    FF2 = S(K2) * DY1 * DY1 * DY1
    F1 = (FF1 + FF2) * DELI
    F2 = DY1 * ((U(K2) / DK) - (S(K2) * DK) / 6.0D0)
    F3 = DY * ((U(K1) / DK) - (S(K1) * DK) / 6.0D0)
    EVAL = F1 + F2 + F3
    RETURN

    ! Finished.

    !+----------------------------------------------------------------------
    !
    !  Copyright (C) 2008
    !  IERS Conventions Center
    !
    !  ==================================
    !  IERS Conventions Software License
    !  ==================================
    !
    !  NOTICE TO USER:
    !
    !  BY USING THIS SOFTWARE YOU ACCEPT THE FOLLOWING TERMS AND CONDITIONS
    !  WHICH APPLY TO ITS USE.
    !
    !  1. The Software is provided by the IERS Conventions Center ("the
    !     Center").
    !
    !  2. Permission is granted to anyone to use the Software for any
    !     purpose, including commercial applications, free of charge,
    !     subject to the conditions and restrictions listed below.
    !
    !  3. You (the user) may adapt the Software and its algorithms for your
    !     own purposes and you may distribute the resulting "derived work"
    !     to others, provided that the derived work complies with the
    !     following requirements:
    !
    !     a) Your work shall be clearly identified so that it cannot be
    !        mistaken for IERS Conventions software and that it has been
    !        neither distributed by nor endorsed by the Center.
    !
    !     b) Your work (including source code) must contain descriptions of
    !        how the derived work is based upon and/or differs from the
    !        original Software.
    !
    !     c) The name(s) of all modified routine(s) that you distribute
    !        shall be changed.
    !
    !     d) The origin of the IERS Conventions components of your derived
    !        work must not be misrepresented; you must not claim that you
    !        wrote the original Software.
    !
    !     e) The source code must be included for all routine(s) that you
    !        distribute.  This notice must be reproduced intact in any
    !        source distribution.
    !
    !  4. In any published work produced by the user and which includes
    !     results achieved by using the Software, you shall acknowledge
    !     that the Software was used in obtaining those results.
    !
    !  5. The Software is provided to the user "as is" and the Center makes
    !     no warranty as to its use or performance.   The Center does not
    !     and cannot warrant the performance or results which the user may
    !     obtain by using the Software.  The Center makes no warranties,
    !     express or implied, as to non-infringement of third party rights,
    !     merchantability, or fitness for any particular purpose.  In no
    !     event will the Center be liable to the user for any consequential,
    !     incidental, or special damages, including any lost profits or lost
    !     savings, even if a Center representative has been advised of such
    !     damages, or for any claim by any third party.
    !
    !  Correspondence concerning IERS Conventions software should be
    !  addressed as follows:
    !
    !                     Gerard Petit
    !     Internet email: gpetit[at]bipm.org
    !     Postal address: IERS Conventions Center
    !                     Time, frequency and gravimetry section, BIPM
    !                     Pavillon de Breteuil
    !                     92312 Sevres  FRANCE
    !
    !     or
    !
    !                     Brian Luzum
    !     Internet email: brian.luzum[at]usno.navy.mil
    !     Postal address: IERS Conventions Center
    !                     Earth Orientation Department
    !                     3450 Massachusetts Ave, NW
    !                     Washington, DC 20392
    !
    !
    !-----------------------------------------------------------------------
END

SUBROUTINE ETUTC (YEAR, DELTA)
    !+
    !  - - - - - - - - -
    !   E T U T C
    !  - - - - - - - - -
    !
    !  This routine is part of the International Earth Rotation and
    !  Reference Systems Service (IERS) Conventions software collection.
    !
    !  The purpose of the subroutine is to compute the difference, delta,
    !  between Epheremis Time (ET) and Coordinated Universal Time (UTC).
    !
    !  In general, Class 1, 2, and 3 models represent physical effects that
    !  act on geodetic parameters while canonical models provide lower-level
    !  representations or basic computations that are used by Class 1, 2, or
    !  3 models.
    !
    !  Status: Canonical model
    !
    !     Class 1 models are those recommended to be used a priori in the
    !     reduction of raw space geodetic data in order to determine
    !     geodetic parameter estimates.
    !     Class 2 models are those that eliminate an observational
    !     singularity and are purely conventional in nature.
    !     Class 3 models are those that are not required as either Class
    !     1 or 2.
    !     Canonical models are accepted as is and cannot be classified as a
    !     Class 1, 2, or 3 model.
    !
    !  Given:
    !     year           d      decimal year (Note 1)
    !
    !  Returned:
    !     delta          d      ET - UTC (Note 2)
    !
    !     :------------------------------------------:
    !     :                                          :
    !     :                 IMPORTANT                :
    !     :                                          :
    !     :  A new version of this routine must be   :
    !     :  produced whenever a new leap second is  :
    !     :  announced.  There are three items to    :
    !     :  change on each such occasion:           :
    !     :                                          :
    !     :  1) Update the nstep variable            :
    !     :  2) Update the arrays st and si          :
    !     :  3) Change date of latest leap second    :
    !     :                                          :
    !     :  Latest leap second:  2017 January 1     :
    !     :                                          :
    !     :__________________________________________:
    !
    !  Notes:
    !
    !  1) This subroutine is valid only from 1700.-until next leap second.
    !     Currently, this is up to 2009.5.
    !
    !  2) The expression used in given in seconds.
    !
    !  3) Leap second table in GAMIT UTC (and UT) is the time most
    !     often used (e.g. in time signals)
    !
    !  Test case:
    !     given input: year = 2007.0
    !
    !     expected output: delta = 65.1840000000000 seconds
    !
    !  References:
    !
    !     Broucke, R. A., Explanatory Supplement American Ephemeris &
    !     Nautical Almanac (cf Comm CACM, 11, 657 (1968) and 15, 918 (1972)),
    !     p. 90 (Tables)
    !
    !     Petit, G. and Luzum, B. (eds.), IERS Conventions (2010),
    !     IERS Technical Note No. 36, BKG (2010)
    !
    !  Revisions:
    !  2009 April 22 B.E. Stetzler    Added header and copyright and
    !                                 provided test case
    !  2009 August 19 B.E. Stetzler   Capitalized all variables for FORTRAN
    !                                 77 compatibility
    !-----------------------------------------------------------------------

    IMPLICIT NONE

    INTEGER I, N, NSTEP
    PARAMETER (NSTEP = 27)
    REAL*8 D, DELTA, FRAC, ST, SI, TX, TY, YEAR
    DIMENSION D(142), TX(39), TY(39), ST(NSTEP), SI(NSTEP)

    ! si gives amount of step, at the times given in st

    DATA SI/27*1./
    DATA ST/1972.5, 1973.0, 1974.0, 1975.0, 1976.0, 1977.0, 1978.0, &
            1979.0, 1980.0, 1981.5, 1982.5, 1983.5, 1985.5, 1988.0, &
            1990.0, 1991.0, 1992.5, 1993.5, 1994.5, 1996.0, 1997.5, &
            1999.0, 2006.0, 2009.0, 2012.5, 2015.5, 2017.0/

    DATA D/ 5.15, 4.64, 5.36, 3.49, 3.27, 2.45, 4.03, 1.76, 3.30, &
            1.00, 2.42, 0.94, 2.31, 2.27, -0.22, 0.03, -0.05, -0.06, -0.57, &
            0.03, -0.47, 0.98, -0.86, 2.45, 0.22, 0.37, 2.79, 1.20, 3.52, &
            1.17, 2.67, 3.06, 2.66, 2.97, 3.28, 3.31, 3.33, 3.23, 3.60, &
            3.52, 4.27, 2.68, 2.75, 2.67, 1.94, 1.39, 1.66, 0.88, 0.33, &
            -0.17, -1.88, -3.43, -4.05, -5.77, -7.06, -7.36, -7.67, -7.64, -7.93, &
            -7.82, -8.35, -7.91, -8.03, -9.14, -8.18, -7.88, -7.62, -7.17, -8.14, &
            -7.59, -7.17, -7.94, -8.23, -7.88, -7.68, -6.94, -6.89, -7.11, -5.87, &
            -5.04, -3.90, -2.87, -0.58, 0.71, 1.80, 3.08, 4.63, 5.86, 7.21, &
            8.58, 10.50, 12.10, 12.49, 14.41, 15.59, 15.81, 17.52, 19.01, 18.39, &
            19.55, 20.36, 21.01, 21.81, 21.76, 22.35, 22.68, 22.94, 22.93, 22.69, &
            22.94, 23.20, 23.31, 23.63, 23.47, 23.68, 23.62, 23.53, 23.59, 23.99, &
            23.80, 24.20, 24.99, 24.97, 25.72, 26.21, 26.37, 26.89, 27.68, 28.13, &
            28.94, 29.42, 29.66, 30.29, 30.96, 31.09, 31.59, 32.06, 31.82, 32.69, &
            33.05, 33.16, 33.59/
    DATA TX/61.5, &
            62., 62.5, 63., 63.5, 64., 64.5, 65., &
            65.5, 66., 66.5, 67., 67.5, 68., 68.25, &
            68.5, 68.75, 69., 69.25, 69.5, 69.75, 70., &
            70.25, 70.5, 70.75, 71., 71.085, 71.162, 71.247, &
            71.329, 71.414, 71.496, 71.581, 71.666, 71.748, 71.833, &
            71.915, 71.999, 72.0/
    DATA TY/33.59, &
            34.032, 34.235, 34.441, 34.644, 34.95, 35.286, 35.725, &
            36.16, 36.498, 36.968, 37.444, 37.913, 38.39, 38.526, &
            38.76, 39., 39.238, 39.472, 39.707, 39.946, 40.185, &
            40.42, 40.654, 40.892, 41.131, 41.211, 41.284, 41.364, &
            41.442, 41.522, 41.600, 41.680, 41.761, 41.838, 41.919, &
            41.996, 42.184, 42.184/

    !  For the oldest epochs, use approximations

    IF(YEAR.LT.1700.0D0) THEN
        DELTA = 0.0D0
        RETURN
    ENDIF
    IF(YEAR.LT.1785.0D0) THEN
        DELTA = (YEAR - 1750.0D0) / 5.0D0
        RETURN
    ENDIF
    IF(YEAR.LT.1820.5D0) THEN
        DELTA = 6.0D0
        RETURN
    ENDIF

    !  For 1820.5 to 1961.5, data is spaced at yearly intervals

    IF(YEAR.LT.1961.5D0) THEN
        N = YEAR - 1819.5
        FRAC = YEAR - (1819.5 + N)
        DELTA = (D(N + 1) - D(N)) * FRAC + D(N)
        RETURN
    ENDIF

    !  For 1961.5 to 1972.0, interpolate between unequispaced data

    IF(YEAR.LT.1972.0D0) THEN
        DO 150 I = 1, 38
            IF(YEAR - 1900.0D0.EQ.TX(I)) THEN
                DELTA = TY(I)
                RETURN
            ENDIF
            IF(YEAR - 1900.0D0.LT.TX(I)) THEN
                DELTA = TY(I - 1) + (TY(I) - TY(I - 1)) * &
                        ((YEAR - 1900.0D0 - TX(I - 1)) / (TX(I) - TX(I - 1)))
                RETURN
            ENDIF
        150     CONTINUE
    ENDIF

    !--------------------------------------------------------------------------*
    !   after 1972 et-utc has only step offsets. st is the array of step times,*
    !   and si is the step sizes (an added second is +1.)                      *
    !--------------------------------------------------------------------------*
    DELTA = 42.184D0
    DO 250 I = 1, NSTEP
        IF(YEAR.GE.ST(I)) DELTA = DELTA + SI(I)
        IF(YEAR.LT.ST(I)) RETURN
    250   CONTINUE
    RETURN

    ! Finished.

    !+----------------------------------------------------------------------
    !
    !  Copyright (C) 2008
    !  IERS Conventions Center
    !
    !  ==================================
    !  IERS Conventions Software License
    !  ==================================
    !
    !  NOTICE TO USER:
    !
    !  BY USING THIS SOFTWARE YOU ACCEPT THE FOLLOWING TERMS AND CONDITIONS
    !  WHICH APPLY TO ITS USE.
    !
    !  1. The Software is provided by the IERS Conventions Center ("the
    !     Center").
    !
    !  2. Permission is granted to anyone to use the Software for any
    !     purpose, including commercial applications, free of charge,
    !     subject to the conditions and restrictions listed below.
    !
    !  3. You (the user) may adapt the Software and its algorithms for your
    !     own purposes and you may distribute the resulting "derived work"
    !     to others, provided that the derived work complies with the
    !     following requirements:
    !
    !     a) Your work shall be clearly identified so that it cannot be
    !        mistaken for IERS Conventions software and that it has been
    !        neither distributed by nor endorsed by the Center.
    !
    !     b) Your work (including source code) must contain descriptions of
    !        how the derived work is based upon and/or differs from the
    !        original Software.
    !
    !     c) The name(s) of all modified routine(s) that you distribute
    !        shall be changed.
    !
    !     d) The origin of the IERS Conventions components of your derived
    !        work must not be misrepresented; you must not claim that you
    !        wrote the original Software.
    !
    !     e) The source code must be included for all routine(s) that you
    !        distribute.  This notice must be reproduced intact in any
    !        source distribution.
    !
    !  4. In any published work produced by the user and which includes
    !     results achieved by using the Software, you shall acknowledge
    !     that the Software was used in obtaining those results.
    !
    !  5. The Software is provided to the user "as is" and the Center makes
    !     no warranty as to its use or performance.   The Center does not
    !     and cannot warrant the performance or results which the user may
    !     obtain by using the Software.  The Center makes no warranties,
    !     express or implied, as to non-infringement of third party rights,
    !     merchantability, or fitness for any particular purpose.  In no
    !     event will the Center be liable to the user for any consequential,
    !     incidental, or special damages, including any lost profits or lost
    !     savings, even if a Center representative has been advised of such
    !     damages, or for any claim by any third party.
    !
    !  Correspondence concerning IERS Conventions software should be
    !  addressed as follows:
    !
    !                     Gerard Petit
    !     Internet email: gpetit[at]bipm.org
    !     Postal address: IERS Conventions Center
    !                     Time, frequency and gravimetry section, BIPM
    !                     Pavillon de Breteuil
    !                     92312 Sevres  FRANCE
    !
    !     or
    !
    !                     Brian Luzum
    !     Internet email: brian.luzum[at]usno.navy.mil
    !     Postal address: IERS Conventions Center
    !                     Earth Orientation Department
    !                     3450 Massachusetts Ave, NW
    !                     Washington, DC 20392
    !
    !
    !-----------------------------------------------------------------------
END